server: 
  port: 9009
spring: 
  application:  
    name: tensquare-sms #指定服务名
  rabbitmq:
    host: 192.168.56.3

aliyun:
  sms:
    accessKeyId: LTAI4GBbJzTZYS9tX1YMAvv1
    accessKeySecret: q9ZVhhbjLnVdOKDhyoRF6pV4U9puSS
    template_code: SMS_190268578
    sign_name: 刘家毅短信的验证码